"""
Q1 Voice Agent — Leads API Router.

Endpoints for inspecting and managing commercial loan leads generated by the voice agent.
"""

from __future__ import annotations

from typing import Any, Optional

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel

from app.services.leads import get_lead_service

router = APIRouter()


class CreateLeadRequest(BaseModel):
    call_id: str
    fields: dict[str, Any]
    qualification_status: str = "ELIGIBLE"
    recommended_product: Optional[str] = None
    contact_permission: bool = True
    notes: str = ""


@router.get("")
async def list_leads() -> list[dict[str, Any]]:
    """List all commercial loan leads."""
    service = get_lead_service()
    return [l.model_dump(mode="json") for l in service.list_leads()]


@router.get("/{lead_id}")
async def get_lead(lead_id: str) -> dict[str, Any]:
    """Get single lead by lead_id."""
    service = get_lead_service()
    lead = service.get_lead(lead_id)
    if not lead:
        raise HTTPException(status_code=404, detail="Lead not found")
    return lead.model_dump(mode="json")


@router.post("")
async def create_lead(request: CreateLeadRequest) -> dict[str, Any]:
    """Create or update a lead."""
    service = get_lead_service()
    lead = service.create_or_update_lead(
        call_id=request.call_id,
        qualification_data=request.fields,
        qualification_status=request.qualification_status,
        recommended_product=request.recommended_product,
        contact_permission=request.contact_permission,
        notes=request.notes,
    )
    return lead.model_dump(mode="json")
